<script lang="ts">
  // The icon a model chose for a project folder from the catalog in folder-icons.json, or the
  // folder mark for a name this release does not know.
  import {
    Accessibility,
    Activity,
    AlarmClock,
    Ambulance,
    Anchor,
    Anvil,
    Aperture,
    AppWindow,
    Apple,
    Archive,
    Atom,
    AudioLines,
    AudioWaveform,
    Award,
    Axe,
    Baby,
    Backpack,
    BadgeCheck,
    Banknote,
    BatteryCharging,
    Bed,
    Beer,
    Bike,
    Binary,
    Bird,
    Bitcoin,
    Blend,
    Blocks,
    Bluetooth,
    Bone,
    BookA,
    BookOpen,
    BookOpenText,
    Bot,
    BowArrow,
    Box,
    Boxes,
    Braces,
    Brain,
    BrainCircuit,
    Briefcase,
    Brush,
    Bug,
    Building2,
    Bus,
    Cake,
    Calculator,
    Calendar,
    CalendarCheck,
    Camera,
    Car,
    Caravan,
    Carrot,
    Castle,
    Cat,
    ChartCandlestick,
    ChartColumn,
    ChartGantt,
    ChartLine,
    ChartNetwork,
    ChartPie,
    ChartScatter,
    ChefHat,
    ChessKnight,
    Church,
    CircuitBoard,
    Clapperboard,
    ClipboardList,
    Clock,
    Cloud,
    CloudCog,
    CloudRain,
    CloudSun,
    Clover,
    Code,
    CodeXml,
    Coffee,
    Cog,
    Coins,
    Compass,
    Component,
    Construction,
    Contact,
    Container,
    Cookie,
    CookingPot,
    Cpu,
    CreditCard,
    Croissant,
    Crosshair,
    Crown,
    Cuboid,
    CupSoda,
    Database,
    DatabaseBackup,
    DatabaseZap,
    Dices,
    Disc3,
    Dna,
    Dog,
    DraftingCompass,
    Drama,
    Drone,
    Droplets,
    Drum,
    Dumbbell,
    Ear,
    Earth,
    Egg,
    Eye,
    Factory,
    Feather,
    FileCode,
    FileText,
    Files,
    Film,
    Fish,
    Flag,
    Flame,
    FlaskConical,
    Flower,
    Folder,
    FolderGit2,
    FolderKanban,
    Footprints,
    Frame,
    Fuel,
    Gamepad2,
    Gavel,
    Gem,
    Ghost,
    Gift,
    GitBranch,
    GitGraph,
    GitPullRequest,
    Globe,
    Goal,
    Gpu,
    GraduationCap,
    Guitar,
    Hamburger,
    Hammer,
    HandHeart,
    Handshake,
    HardDrive,
    Hash,
    Headphones,
    Heart,
    HeartPulse,
    Hospital,
    Hotel,
    Hourglass,
    House,
    HousePlug,
    IceCreamCone,
    IdCard,
    Image,
    Images,
    Inbox,
    Infinity,
    Joystick,
    Key,
    KeyRound,
    Keyboard,
    KeyboardMusic,
    Lamp,
    Landmark,
    Languages,
    Laptop,
    Layers,
    LayoutDashboard,
    LayoutTemplate,
    Leaf,
    Library,
    LifeBuoy,
    Lightbulb,
    Link,
    ListChecks,
    ListTodo,
    Lock,
    Luggage,
    Magnet,
    Mail,
    Map,
    MapPin,
    Medal,
    Megaphone,
    MemoryStick,
    MessageSquare,
    MessagesSquare,
    Mic,
    MicVocal,
    Microchip,
    Microscope,
    Monitor,
    Moon,
    MoonStar,
    Mountain,
    MountainSnow,
    MousePointer2,
    Music,
    Network,
    Newspaper,
    Notebook,
    NotebookPen,
    NotebookText,
    Orbit,
    Origami,
    Package,
    PackageOpen,
    PaintBucket,
    Paintbrush,
    Palette,
    PanelsTopLeft,
    PartyPopper,
    PawPrint,
    PenTool,
    Pencil,
    PencilRuler,
    PersonStanding,
    Pi,
    Piano,
    Pickaxe,
    PiggyBank,
    Pill,
    Pizza,
    Plane,
    Plug,
    Popcorn,
    Presentation,
    Printer,
    Puzzle,
    Quote,
    Rabbit,
    Radio,
    RadioTower,
    Rainbow,
    Receipt,
    Recycle,
    Regex,
    Rocket,
    Router,
    Rss,
    Ruler,
    Sailboat,
    Salad,
    Satellite,
    SatelliteDish,
    Scale,
    ScanEye,
    ScanQrCode,
    School,
    Scissors,
    Scroll,
    ScrollText,
    Send,
    Server,
    ServerCog,
    Shapes,
    Sheet,
    Shell,
    Shield,
    ShieldCheck,
    Ship,
    Shirt,
    ShoppingBag,
    ShoppingCart,
    Sigma,
    Skull,
    Smartphone,
    Snail,
    Snowflake,
    Sofa,
    SolarPanel,
    Sparkles,
    Speaker,
    SpellCheck,
    Spline,
    Sprout,
    SquareFunction,
    SquareKanban,
    SquareTerminal,
    Squirrel,
    Stamp,
    Stethoscope,
    Sticker,
    Store,
    Sun,
    Sunrise,
    Sword,
    Swords,
    Syringe,
    Table,
    TabletSmartphone,
    Tag,
    Target,
    Telescope,
    Tent,
    Terminal,
    TestTubeDiagonal,
    TestTubes,
    Thermometer,
    Ticket,
    Timer,
    ToyBrick,
    Tractor,
    TrainFront,
    TreePalm,
    TreePine,
    Trees,
    TrendingUp,
    Trophy,
    Truck,
    Turtle,
    Tv,
    Type,
    Umbrella,
    University,
    Usb,
    User,
    Users,
    Utensils,
    Video,
    Volleyball,
    Vote,
    Wallet,
    WandSparkles,
    Warehouse,
    Watch,
    Webcam,
    Webhook,
    Wheat,
    Wifi,
    Wind,
    Wine,
    Workflow,
    Wrench,
    Zap,
  } from '@lucide/svelte';
  let { icon, size = 14 }: { icon?: string; size?: number } = $props();
  const icons: Record<string, typeof Folder> = {
    folder: Folder,
    code: Code,
    'code-xml': CodeXml,
    braces: Braces,
    terminal: Terminal,
    'square-terminal': SquareTerminal,
    bug: Bug,
    'git-branch': GitBranch,
    'git-pull-request': GitPullRequest,
    'git-graph': GitGraph,
    'folder-git-2': FolderGit2,
    'folder-kanban': FolderKanban,
    package: Package,
    boxes: Boxes,
    container: Container,
    blocks: Blocks,
    component: Component,
    puzzle: Puzzle,
    plug: Plug,
    webhook: Webhook,
    workflow: Workflow,
    cog: Cog,
    wrench: Wrench,
    hammer: Hammer,
    'file-code': FileCode,
    binary: Binary,
    regex: Regex,
    'square-function': SquareFunction,
    hash: Hash,
    'test-tube-diagonal': TestTubeDiagonal,
    spline: Spline,
    bot: Bot,
    brain: Brain,
    'brain-circuit': BrainCircuit,
    sparkles: Sparkles,
    'wand-sparkles': WandSparkles,
    'message-square': MessageSquare,
    'messages-square': MessagesSquare,
    'audio-waveform': AudioWaveform,
    'scan-eye': ScanEye,
    database: Database,
    'database-zap': DatabaseZap,
    'database-backup': DatabaseBackup,
    'chart-line': ChartLine,
    'chart-column': ChartColumn,
    'chart-pie': ChartPie,
    'chart-scatter': ChartScatter,
    'chart-network': ChartNetwork,
    'chart-candlestick': ChartCandlestick,
    'chart-gantt': ChartGantt,
    table: Table,
    sheet: Sheet,
    globe: Globe,
    earth: Earth,
    server: Server,
    'server-cog': ServerCog,
    cloud: Cloud,
    'cloud-cog': CloudCog,
    'hard-drive': HardDrive,
    network: Network,
    router: Router,
    wifi: Wifi,
    'radio-tower': RadioTower,
    'satellite-dish': SatelliteDish,
    link: Link,
    rss: Rss,
    mail: Mail,
    send: Send,
    'shield-check': ShieldCheck,
    shield: Shield,
    lock: Lock,
    'key-round': KeyRound,
    'scan-qr-code': ScanQrCode,
    monitor: Monitor,
    laptop: Laptop,
    smartphone: Smartphone,
    'tablet-smartphone': TabletSmartphone,
    'app-window': AppWindow,
    'layout-dashboard': LayoutDashboard,
    'panels-top-left': PanelsTopLeft,
    'layout-template': LayoutTemplate,
    keyboard: Keyboard,
    'mouse-pointer-2': MousePointer2,
    cpu: Cpu,
    gpu: Gpu,
    'memory-stick': MemoryStick,
    'circuit-board': CircuitBoard,
    microchip: Microchip,
    usb: Usb,
    bluetooth: Bluetooth,
    printer: Printer,
    headphones: Headphones,
    speaker: Speaker,
    tv: Tv,
    watch: Watch,
    webcam: Webcam,
    drone: Drone,
    'battery-charging': BatteryCharging,
    'solar-panel': SolarPanel,
    'gamepad-2': Gamepad2,
    joystick: Joystick,
    dices: Dices,
    swords: Swords,
    sword: Sword,
    'bow-arrow': BowArrow,
    castle: Castle,
    crown: Crown,
    trophy: Trophy,
    medal: Medal,
    target: Target,
    crosshair: Crosshair,
    ghost: Ghost,
    skull: Skull,
    pickaxe: Pickaxe,
    axe: Axe,
    anvil: Anvil,
    'toy-brick': ToyBrick,
    'chess-knight': ChessKnight,
    map: Map,
    compass: Compass,
    flag: Flag,
    'scroll-text': ScrollText,
    scroll: Scroll,
    gem: Gem,
    coins: Coins,
    backpack: Backpack,
    drama: Drama,
    'party-popper': PartyPopper,
    palette: Palette,
    brush: Brush,
    paintbrush: Paintbrush,
    'paint-bucket': PaintBucket,
    'pen-tool': PenTool,
    pencil: Pencil,
    'pencil-ruler': PencilRuler,
    'drafting-compass': DraftingCompass,
    ruler: Ruler,
    shapes: Shapes,
    box: Box,
    cuboid: Cuboid,
    blend: Blend,
    layers: Layers,
    frame: Frame,
    image: Image,
    images: Images,
    camera: Camera,
    aperture: Aperture,
    film: Film,
    clapperboard: Clapperboard,
    video: Video,
    popcorn: Popcorn,
    music: Music,
    'keyboard-music': KeyboardMusic,
    piano: Piano,
    guitar: Guitar,
    drum: Drum,
    mic: Mic,
    'mic-vocal': MicVocal,
    radio: Radio,
    'audio-lines': AudioLines,
    'disc-3': Disc3,
    'book-open': BookOpen,
    'notebook-pen': NotebookPen,
    feather: Feather,
    type: Type,
    quote: Quote,
    newspaper: Newspaper,
    presentation: Presentation,
    scissors: Scissors,
    sticker: Sticker,
    origami: Origami,
    'graduation-cap': GraduationCap,
    school: School,
    university: University,
    'book-open-text': BookOpenText,
    library: Library,
    notebook: Notebook,
    'notebook-text': NotebookText,
    'book-a': BookA,
    languages: Languages,
    'spell-check': SpellCheck,
    atom: Atom,
    dna: Dna,
    microscope: Microscope,
    telescope: Telescope,
    'flask-conical': FlaskConical,
    'test-tubes': TestTubes,
    calculator: Calculator,
    sigma: Sigma,
    pi: Pi,
    infinity: Infinity,
    lightbulb: Lightbulb,
    magnet: Magnet,
    orbit: Orbit,
    rocket: Rocket,
    satellite: Satellite,
    'moon-star': MoonStar,
    stethoscope: Stethoscope,
    'heart-pulse': HeartPulse,
    pill: Pill,
    syringe: Syringe,
    hospital: Hospital,
    ambulance: Ambulance,
    bone: Bone,
    activity: Activity,
    thermometer: Thermometer,
    ear: Ear,
    eye: Eye,
    accessibility: Accessibility,
    'person-standing': PersonStanding,
    briefcase: Briefcase,
    'building-2': Building2,
    store: Store,
    'shopping-cart': ShoppingCart,
    'shopping-bag': ShoppingBag,
    receipt: Receipt,
    'credit-card': CreditCard,
    wallet: Wallet,
    banknote: Banknote,
    'piggy-bank': PiggyBank,
    bitcoin: Bitcoin,
    landmark: Landmark,
    scale: Scale,
    gavel: Gavel,
    'trending-up': TrendingUp,
    handshake: Handshake,
    users: Users,
    user: User,
    contact: Contact,
    'id-card': IdCard,
    megaphone: Megaphone,
    'clipboard-list': ClipboardList,
    'square-kanban': SquareKanban,
    'list-todo': ListTodo,
    'list-checks': ListChecks,
    calendar: Calendar,
    'calendar-check': CalendarCheck,
    clock: Clock,
    timer: Timer,
    hourglass: Hourglass,
    'alarm-clock': AlarmClock,
    inbox: Inbox,
    'file-text': FileText,
    files: Files,
    archive: Archive,
    'package-open': PackageOpen,
    truck: Truck,
    warehouse: Warehouse,
    factory: Factory,
    construction: Construction,
    tag: Tag,
    ticket: Ticket,
    gift: Gift,
    award: Award,
    'badge-check': BadgeCheck,
    stamp: Stamp,
    vote: Vote,
    house: House,
    'house-plug': HousePlug,
    sofa: Sofa,
    bed: Bed,
    hotel: Hotel,
    lamp: Lamp,
    key: Key,
    utensils: Utensils,
    'chef-hat': ChefHat,
    'cooking-pot': CookingPot,
    coffee: Coffee,
    'cup-soda': CupSoda,
    pizza: Pizza,
    hamburger: Hamburger,
    apple: Apple,
    carrot: Carrot,
    salad: Salad,
    cake: Cake,
    croissant: Croissant,
    wine: Wine,
    beer: Beer,
    cookie: Cookie,
    'ice-cream-cone': IceCreamCone,
    egg: Egg,
    shirt: Shirt,
    baby: Baby,
    dog: Dog,
    cat: Cat,
    'paw-print': PawPrint,
    bird: Bird,
    fish: Fish,
    rabbit: Rabbit,
    turtle: Turtle,
    squirrel: Squirrel,
    snail: Snail,
    dumbbell: Dumbbell,
    bike: Bike,
    footprints: Footprints,
    volleyball: Volleyball,
    goal: Goal,
    car: Car,
    bus: Bus,
    'train-front': TrainFront,
    plane: Plane,
    ship: Ship,
    sailboat: Sailboat,
    anchor: Anchor,
    caravan: Caravan,
    luggage: Luggage,
    'map-pin': MapPin,
    fuel: Fuel,
    tractor: Tractor,
    church: Church,
    heart: Heart,
    'hand-heart': HandHeart,
    'life-buoy': LifeBuoy,
    umbrella: Umbrella,
    tent: Tent,
    leaf: Leaf,
    sprout: Sprout,
    trees: Trees,
    'tree-pine': TreePine,
    'tree-palm': TreePalm,
    flower: Flower,
    clover: Clover,
    wheat: Wheat,
    mountain: Mountain,
    'mountain-snow': MountainSnow,
    droplets: Droplets,
    sun: Sun,
    moon: Moon,
    'cloud-sun': CloudSun,
    'cloud-rain': CloudRain,
    snowflake: Snowflake,
    flame: Flame,
    zap: Zap,
    wind: Wind,
    rainbow: Rainbow,
    sunrise: Sunrise,
    recycle: Recycle,
    shell: Shell,
  };
  const Icon = $derived((icon && Object.hasOwn(icons, icon) ? icons[icon] : undefined) ?? Folder);
</script>

<Icon {size} aria-hidden="true" />
